const text = `The Mar Thoma Church had a humble beginning in Kerala, India. It had expanded its boundaries to different corners of the continents of the world.
The Marthoma church in United Kingdom was establishment dates back to 1930. In August 1948 Juhanon Mar Thoma Metropolitan, head of the Malankara Mar Thoma Syrian Church, passed through London to attend the Meeting of World Council of Churches in Amsterdam. Though only very few Marthomites lived in London at that time, a holy communion service was conducted, the first Mar Thoma Holy Communion service held in Europe.
In the early 1950s, a few Marthomites came to the U.K as students for higher studies and for employment. Once a month they met in the chapel of the Indian YMCA Students’ Hostel in London. At that time there were no other Malayali Christian services in the UK. This encouraged other Christian denominations to also participate in the worship.
In 1957, Mr O.V. Alexander was appointed as the General Secretary of the Indian YMCA and Hostel, London, where the first Mar Thoma congregation was approved. During the 1970s, more Marthomites and other Christians came to England from Malaysia, Singapore, Uganda, Zambia, India and many other countries in the African Great Lakes. In 1979 the congregation moved to St. Mary’s Parish Church Newington in Kennington from the YMCA due to increased participation from those that had arrived in the UK. Although we had services once/ twice a month, most of our members took membership in the local parishes of the Church of England, with whom the Mar Thoma Church had full communion.
During this period the community was supported by the following clergy - Rev. V V Alexander; Rt Rev. Joseph Mar Thoma; Very Rev. P M George; Rt Rev. Easow Mar Timotheus and Rev. Dr Philip Varghese. Rev. Dr Abrham Philip, the first vicar was appointed in 1982. 1.[2][3] Later on Rev. Dr George Mathew, Rev. A T Zachariah, Rev. Aby T Mammen was appointed as Vicars.
Afterwards,this group, with a congregational status was recognised as a parish. In 1989 the parish moved to St. Katharine Cree Church in Central London. Several Bishops of the Church visited from time to time. In 1996, the Episcopal Synod of the Mar Thoma Church decided to split the UK parish in two, creating St. Johns Mar Thoma Church, Hounslow and St James Mar Thoma Church, in Central London.
The Church began as a small prayer group in Queens, New York. In 1972 this was approved as a congregation and later moved to Manhattan. In May 1975 ‘’Mar Thoma Congregation of Greater New York" was formed and K.S. Mathew appointed as its vicar. The first congregation in USA that was approved as a parish of the Malankara Mar Thoma Syrian Church in 1976 was in New York.
As members increased and more Marthomites began to settle down in other parts of USA and Canada, more congregations were formed and later they became parishes.
In Houston, Texas, the first Mar Thoma church building in USA was consecrated by Thomas Mar Athanasius Suffragan Metropolitan, on July 15, 1984 and was named ‘’Trinity Mar Thoma church Houston".`;

export default text;